### ISSUE TITLE
Sugestão de melhoria: Detalhar o modelo OSI

### ISSUE THREAD

**Issue by ericoschuch** [bl4cktux89/bl4cktux89-blog#3]
OSI é algo desconhecido por iniciantes. Um detalhamento exemplificado de cada camada serviria como introdução, impedindo que o leitor tenha que deixar o artigo para procurar mais informações.

Como exemplo, apresento a analogia da camada e o que trata, sendo:

7 - Aplicação : É a informação que a aplicação (executável em um computador) processa. É o que normalmente o usuário pode ver. http/SMTP/IMAP/...
6 - Apresentação: Transforma a informação. Onde ocorre criptografia: ssl/tls...
5 - Sessão: Controle de fluxo, erros: onde ocorre ordenação por controle de fluxo e retransmissão por erros: número de sequência tcp, tcp checksum e ack
4 - transporte: os dados tem controle de fluxo(tcp) ou não(udp)
3 - rede: determinar qual próximo destino usar pela diferença entre IP e rede(rota)
2 - enlace: basicamente o MAC da interface de rede. Exato ponto entre estar dentro ou fora do equipamento.
1 - física: dados binários (ou sua representação analógica) transmitidos em um meio físico

Disclaimer: No CCNA lá em 2000, insistia com o instrutor que os controles de fluxo e ordenação do tcp é a sessão e isto deveria colocar tcp como sessão. Mas na prova oficial e documentação estava como 4 transporte pois, segundo ele, a função mais inferior do protocolo era o que classificava ele na camada OSI. Nunca  fui a fundo e assim nunca achei documentação oficial do motivo que a Cisco coloca tcp num todo como apenas transporte.

**Comment by bl4cktux89** [comment]
Érico, fiz uma explicação breve, pois acredito que para detalhar mais as camadas e os protocolos presentes em cada camada, teria que criar um artigo exclusivo com esse tema.

Sobre essa questão do protocolo TCP, posso estudar melhor a RFC e ver se encontro a resposta para esse questionamento, porque fiquei com uma pulga atrás da orelha também.

Eu mosquei e esqueci de associar um commit exclusivo para a sua issue, abaixo está o trecho inserido:

### Modelo OSI

O modelo *OSI* (Open Systems Intercommunication, em português, Intercomunicação de Sistemas Abertos) foi desenvolvido pela ISO (International Organization for Standardization, em português, Organização Internacional de Padronização) a partir da necessidade de padronização dos hardwares e protocolos. No início, cada fabricante seguia um padrão proprietário, o que dificultava e até mesmo impossibilitava a comunicação entre equipamentos de diferentes fabricantes, dessa forma, o modelo OSI foi proposto para preencher essas lacunas tendo como principais objetivos:
1. Garantir a comunicação fim-a-fim
2. Permitir a comunicação entre dispositivos de diferentes fabricantes
3. Definir regras para a construção das redes de computadores independe da tecnologia e do alcance geográfico
4. Facilitar o aprendizado da arquitetura das redes
5. Permite que novas tecnologias sejam facilmente implantadas e atualizadas

![Modelo OSI](./.resources/osi-model.png)

O modelo OSI é estruturado em 7 camadas:
1. Física: especificações elétricas e mecânicas, representação dos bits.
2. Enlace de Dados: controle de acesso ao meio físico.
    * Subnível inferior (MAC): controle de acesso ao meio.
    * Subnível superior (LLC): controle lógico do enlace.
3. Rede: roteamento dos pacotes, endereçamento IP, protocolos como ARP e RARP.
4. Transporte: transporte confiável e eficiente entre dispositivos.
    * Protocolos orientados a conexão (TCP).
    * Protocolos não confiáveis e não orientados a conexão (UDP).
5. Sessão: estabelecimento e gerenciamento de sessões entre aplicações.
6. Apresentação: conversão de formatos de dados, compactação e criptografia.
7. Aplicação: interface de interação entre usuário e máquina, protocolos como HTTP, SMTP, FTP.

Os protocolos são associados às camadas de acordo com as suas funcionalidades.
